# Generated by Django 2.0.6 on 2018-08-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-created_time']},
        ),
    ]
